name: Python Code Quality & Tests

on:
  push:
    branches:
      - "main"

jobs:
  dev-depn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Install system dependencies for Cairo and FFmpeg
          run: |
            sudo apt-get update
            sudo apt-get install -y libcairo2-dev pkg-config ffmpeg

      - run: uv pip install -e .

  import-sort:
    runs-on: ubuntu-latest
    needs: [dev-depn]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check --select I --fix

  linting:
    runs-on: ubuntu-latest
    needs: [dev-depn]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .

  formatting:
    runs-on: ubuntu-latest
    needs: [dev-depn]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .

  manim_validation:
    runs-on: ubuntu-latest
    needs: [dev-depn]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Validate Manim Syntax (without full render)
        run: |
          manim -ql -s examples/dotmotion_demo.py PolkadotScene
          manim -ql -s examples/one_min_demo.py OneMinDemo

  build:
    runs-on: [ubuntu-latest]
    needs: [import-sort, linting, formatting, manim_validation]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build
